In [209]:
import numpy as np
import pandas as pd

In [210]:
data=pd.read_csv('drugs1.csv')

In [211]:
data.head()

key  class
0  narcotic narcotics      1
1               drugs      1
2       pshychotropic      1
3          substances      1
4           addiction      1

In [212]:
data.tail()

key  class
206     austere      0
207       belie      0
208  capricious      0
209    cerebral      0
210   congenial      0

In [213]:
data.isnull().sum()

key      0
class    0
dtype: int64

In [214]:
data = data.sample(frac = 1)

In [215]:
data.head(10)

key  class
48                suspicious packaging      1
4                            addiction      1
199                               girl      0
117              URGENT! You have won       0
49   pills that were of unusual colour      1
173                            ironman      0
76            he was not in his senses      1
159                               spam      0
85                          corruption      1
10                            dopamine      1

In [216]:
data.tail()

key  class
124  England v Macedonia - dont miss the goals/team...      0
175                                              catch      0
126  I‰Û÷m going to try for 2 months ha ha only joking      0
8                                           antagonist      1
147                                      anachronistic      0

In [217]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [218]:
x=data['key']
y=data['class']

In [219]:
cv=CountVectorizer()
x = cv.fit_transform(x)

In [220]:
print(x)

  (0, 323)	1
  (0, 253)	1
  (1, 8)	1
  (2, 145)	1
  (3, 359)	1
  (3, 390)	1
  (3, 159)	1
  (3, 382)	1
  (4, 262)	1
  (4, 333)	1
  (4, 371)	1
  (4, 242)	1
  (4, 355)	1
  (4, 83)	1
  (5, 184)	1
  (6, 161)	1
  (6, 367)	1
  (6, 238)	1
  (6, 178)	1
  (6, 169)	1
  (6, 298)	1
  (7, 309)	1
  (8, 94)	1
  (9, 114)	1
  (10, 41)	1
  :	:
  (202, 194)	1
  (202, 90)	1
  (202, 348)	1
  (203, 182)	1
  (204, 87)	1
  (205, 117)	1
  (206, 335)	1
  (206, 124)	1
  (206, 207)	1
  (206, 113)	1
  (206, 219)	1
  (206, 147)	1
  (206, 327)	1
  (206, 235)	1
  (207, 74)	1
  (208, 345)	1
  (208, 190)	1
  (208, 149)	1
  (208, 224)	1
  (208, 139)	1
  (208, 349)	1
  (208, 155)	2
  (208, 246)	1
  (209, 27)	1
  (210, 23)	1


In [221]:
x.toarray()[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [222]:
frequency_ofwords = pd.DataFrame(x.toarray(), columns= cv.get_feature_names() )

C:\Users\divve\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [223]:
frequency_ofwords

abate  abjure  abound  about  abuse  abusing  acting  activity  \
0        0       0       0      0      0        0       0         0   
1        0       0       0      0      0        0       0         0   
2        0       0       0      0      0        0       0         0   
3        0       0       0      0      0        0       0         0   
4        0       0       0      0      0        0       0         0   
..     ...     ...     ...    ...    ...      ...     ...       ...   
206      0       0       0      0      0        0       0         0   
207      0       0       0      0      0        0       0         0   
208      0       0       0      0      0        0       0         0   
209      0       0       0      0      0        0       0         0   
210      0       0       0      0      0        0       0         0   

     addiction  adulterate  ...  word  words  work  wrapped  \
0            0           0  ...     0      0     0        0   
1            1           0  ...     0      0     0        0   
2            0           0  ...     0      0     0        0   
3            0           0  ...     0      0     0        0   
4            0           0  ...     0      0     0        0   
..         ...         ...  ...   ...    ...   ...      ...   
206          0           0  ...     0      0     0        0   
207          0           0  ...     0      0     0        0   
208          0           0  ...     0      0     0        0   
209          0           0  ...     0      0     0        0   
210          0           0  ...     0      0     0        0   

     xxxmobilemovieclub  yaba  yes  you  your  ì_  
0                     0     0    0    0     0   0  
1                     0     0    0    0     0   0  
2                     0     0    0    0     0   0  
3                     0     0    0    1     0   0  
4                     0     0    0    0     0   0  
..                  ...   ...  ...  ...   ...  ..  
206                   0     0    0    0     0   0  
207                   0     0    0    0     0   0  
208                   0     0    0    0     0   0  
209                   0     0    0    0     0   0  
210                   0     0    0    0     0   0  

[211 rows x 393 columns]

In [224]:
x_train, x_test, y_train, y_test = train_test_split(x.toarray(), y, test_size=0.12, random_state=42)

In [225]:
model = MultinomialNB()

In [226]:
model.fit(x_train,y_train)

MultinomialNB()

In [227]:
print("The score for MultinomialNB model over the given data is ",model.score(x_test,y_test)*100)

The score for MultinomialNB model over the given data is  53.84615384615385


# Prediction

In [228]:
text1 = "In Gorakhpur the students are taking the very addictive drugs to win the sports events very easily for there college"
data1 = [text1]

In [229]:
data1=cv.transform(data1).toarray()

In [230]:
prediction1 = model.predict(data1)

In [231]:
predict_score1 = model.predict_proba(data1)

In [232]:
predict_score1

array([[0.30304959, 0.69695041]])

In [233]:
print(prediction1)
if prediction1[0] == 1:
    print("Genuine Reason")
else:
    print("Not a Genuine Reason")

[1]
Genuine Reason


In [234]:
text2 = "you won 100rs in the game"
data2 = [text2]

In [235]:
data2=cv.transform(data2).toarray()

In [236]:
prediction2 = model.predict(data2)

In [237]:
predict_score2=model.predict_proba(data2)

In [238]:
predict_score2

array([[0.85343368, 0.14656632]])

In [239]:
print(prediction2)
if prediction2[0] == 1:
    print("Genuine Reason")
else:
    print("Not a Genuine Reason")

[0]
Not a Genuine Reason


In [240]:
text3 = "kailash ritik afrin muskan vishnu"
data3 = [text3]
data3=cv.transform(data3).toarray()
prediction3 = model.predict(data3)
predict_score3=model.predict_proba(data3)
print(predict_score3)
print(prediction3)
if prediction3[0] == 1:
    print("Genuine Reason")
else:
    print("Not a Genuine Reason")

[[0.48648649 0.51351351]]
[1]
Genuine Reason


In [241]:
text4 = "Here in lucknow narcotic and steroids drugs are being trafficked in gomti nagar"
data4 = [text4]
data4=cv.transform(data4).toarray()
prediction4 = model.predict(data4)
predict_score4=model.predict_proba(data4)
print(predict_score4)
print(prediction4)
if prediction4[0] == 1:
    print("It is a Genuine Reason with ",predict_score4[0][1]*100,"% probabulity")
else:
    print("It is Not a Genuine Reason with ",predict_score4[0][0]*100,"% proabulity")

[[0.00577655 0.99422345]]
[1]
It is a Genuine Reason with  99.42234475225906 % probabulity


# Random Forest classifier

In [242]:
from sklearn.ensemble import RandomForestClassifier
model2 = RandomForestClassifier(n_estimators = 100)
model2.fit(x_train,y_train)

RandomForestClassifier()

In [243]:
print("The score for Random Forest classifier model over the given data is ",model2.score(x_test,y_test)*100)

The score for Random Forest classifier model over the given data is  80.76923076923077


In [244]:
text4 = "Here in lucknow narcotic and steroids drugs are being trafficked in gomti nagar"
data4 = [text4]
data4=cv.transform(data4).toarray()
prediction4 = model2.predict(data4)
predict_score4=model2.predict_proba(data4)
print(predict_score4)
print(prediction4)
if prediction4[0] == 1:
    print("It is a Genuine Reason with ",predict_score4[0][1]*100,"% probabulity")
else:
    print("It is Not a Genuine Reason with ",predict_score4[0][0]*100,"% proabulity")

[[0.02 0.98]]
[1]
It is a Genuine Reason with  98.0 % probabulity


In [245]:
text4 = "kailash ritik afrin muskan vishnu"
data4 = [text4]
data4=cv.transform(data4).toarray()
prediction4 = model2.predict(data4)
predict_score4=model2.predict_proba(data4)
print(predict_score4)
print(prediction4)
if prediction4[0] == 1:
    print("It is a Genuine Reason with ",predict_score4[0][1]*100,"% probabulity")
else:
    print("It is Not a Genuine Reason with ",predict_score4[0][0]*100,"% proabulity")

[[0.88 0.12]]
[0]
It is Not a Genuine Reason with  88.0 % proabulity


In [246]:
text4 = "In Gorakhpur the students are taking the very addictive drugs to win the sports events very easily for there college"
data4 = [text4]
data4=cv.transform(data4).toarray()
prediction4 = model2.predict(data4)
predict_score4=model2.predict_proba(data4)
print(predict_score4)
print(prediction4)
if prediction4[0] == 1:
    print("It is a Genuine Reason with ",predict_score4[0][1]*100,"% probabulity")
else:
    print("It is Not a Genuine Reason with ",predict_score4[0][0]*100,"% proabulity")

[[0.3 0.7]]
[1]
It is a Genuine Reason with  70.0 % probabulity
